// 主窗口与界面入口

export component MainWindow inherits Window {  // 定义一个可以被 Rust 使用的组件，名字为 MainWindow，让其继承一个普通窗口
    width: 900px;
    height: 600px;
    title: "Reignite Project Management";

    Rectangle {  // 卡片区域
        background: #1e1e1e;

        VerticalLayout {
            padding: 40px;
            spacing: 12px;

            Text {  // 显示文字
                text: "Reignite";
                color: #ffffff;
                font-size: 32px;
            }

            Text {
                text: "Manage forgotten projects and bring them back to life.";
                color: #aaaaaa;
                font-size: 16px;
            }
        }
    }

}
